plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - liquid_reading_time
  - liquid_pluralize
  - jekyll-compose
#  - jekyll-analytics

#Serving
host: 0.0.0.0

# Reload
livereload: true

google_analytics: G-W60SL4DRZM

#jekyll_analytics:
#  GoogleAnalytics:
#  id: G-W60SL4DRZM
#  anonymizeIp: true