plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics



#Serving
host: 0.0.0.0

# Reload
livereload: true

jekyll_analytics:
  GoogleAnalytics:
  id: G-W60SL4DRZM
  anonymizeIp: true